# Generated by Django 2.2.11 on 2020-04-23 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['userid']},
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='id',
            new_name='userid',
        ),
    ]
