# Generated by Django 2.2.11 on 2020-04-23 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20200423_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='userid',
            field=models.CharField(default=1, max_length=200),
        ),
        migrations.AddField(
            model_name='orders',
            name='userid',
            field=models.CharField(default=1, max_length=200),
        ),
    ]
