# Generated by Django 2.2.11 on 2020-04-23 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20200423_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlineitem',
            name='userid',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='orders',
            name='userid',
            field=models.CharField(max_length=200),
        ),
    ]
